### ISSUE TITLE
instruction on training?

### ISSUE THREAD

**Issue by gyin94** [tencent-ailab/ICML21_OAXE#2]
can I ask whether it is possible to provide any instruction for training or any other change in fairseq training instructions?

**Comment by NonvolatileMemory** [comment]
sorry for the late reply, the training and inference shell will comming soon.

**Comment by gyin94** [comment]
@NonvolatileMemory can I ask whether there is any update on training instruction? Thanks.

**Comment by NonvolatileMemory** [comment]
@gyin-ai Hello, see readme? If you have any question, feel free to contact me via email.

**Comment by NonvolatileMemory** [comment]
@gyin-ai Updated Now.
