### ISSUE TITLE
Code diff to original fairseq

### ISSUE THREAD

**Issue by SirRob1997** [tencent-ailab/ICML21_OAXE#3]
Can you share the code-diff to the original fairseq implementation so it's clear which parts were added/adapted? This would make things a lot easier to integrate with other papers. Thanks!

**Comment by NonvolatileMemory** [comment]
Hi Rob,
The different file is in https://github.com/tencent-ailab/ICML21_OAXE/blob/master/fairseq/criterions/oaxe.py
